<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MestaSPscSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mesta_s_psc')->insert([
        ['mesto' => 'Bratislava', 'psc' => '81101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Košice', 'psc' => '04001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Prešov', 'psc' => '08001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Žilina', 'psc' => '01001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Banská Bystrica', 'psc' => '97401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nitra', 'psc' => '94901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Trnava', 'psc' => '91701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Martin', 'psc' => '03601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Trenčín', 'psc' => '91101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Poprad', 'psc' => '05801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Prievidza', 'psc' => '97101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zvolen', 'psc' => '96001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Považská Bystrica', 'psc' => '01701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Michalovce', 'psc' => '07101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišská Nová Ves', 'psc' => '05201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Komárno', 'psc' => '94501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Levice', 'psc' => '93401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Humenné', 'psc' => '06601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bardejov', 'psc' => '08501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Liptovský Mikuláš', 'psc' => '03101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ružomberok', 'psc' => '03401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Piešťany', 'psc' => '92101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dunajská Streda', 'psc' => '92901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Žiar nad Hronom', 'psc' => '96501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Topoľčany', 'psc' => '95501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Senica', 'psc' => '90501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Námestovo', 'psc' => '02901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rimavská Sobota', 'psc' => '97901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vranov nad Topľou', 'psc' => '09301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Čadca', 'psc' => '02201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nové Zámky', 'psc' => '94001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Trebišov', 'psc' => '07501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Brezno', 'psc' => '97701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Stará Ľubovňa', 'psc' => '06401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Snina', 'psc' => '06901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dolný Kubín', 'psc' => '02601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kysucké Nové Mesto', 'psc' => '02401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Myjava', 'psc' => '90701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Stropkov', 'psc' => '09101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Sobrance', 'psc' => '07301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Gelnica', 'psc' => '05601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Senec', 'psc' => '90301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Pezinok', 'psc' => '90201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Malacky', 'psc' => '90101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Skalica', 'psc' => '90901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Hlohovec', 'psc' => '92001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vráble', 'psc' => '95212', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zlaté Moravce', 'psc' => '95301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šaľa', 'psc' => '92701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Štúrovo', 'psc' => '94301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Fiľakovo', 'psc' => '98601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tornaľa', 'psc' => '98201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Revúca', 'psc' => '05001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Detva', 'psc' => '96212', 'krajina' => 'Slovensko'],
        ['mesto' => 'Veľký Krtíš', 'psc' => '99001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Poltár', 'psc' => '98701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Krupina', 'psc' => '96301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Banská Štiavnica', 'psc' => '96901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ilava', 'psc' => '01901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Partizánske', 'psc' => '95801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nové Mesto nad Váhom', 'psc' => '91501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Púchov', 'psc' => '02001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bytča', 'psc' => '01401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Turčianske Teplice', 'psc' => '03901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tvrdošín', 'psc' => '02744', 'krajina' => 'Slovensko'],
        ['mesto' => 'Trstená', 'psc' => '02801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Levoča', 'psc' => '05401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kežmarok', 'psc' => '06001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišská Belá', 'psc' => '06101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišské Podhradie', 'psc' => '05304', 'krajina' => 'Slovensko'],
        ['mesto' => 'Sabinov', 'psc' => '08301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Lipany', 'psc' => '08201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Stará Ľubovňa', 'psc' => '06401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Medzilaborce', 'psc' => '06801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Giraltovce', 'psc' => '08701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Svidník', 'psc' => '08901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Lučenec', 'psc' => '98401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Galanta', 'psc' => '92401', 'krajina' => 'Slovensko'],
        ['mesto' => 'Holíč', 'psc' => '90851', 'krajina' => 'Slovensko'],
        ['mesto' => 'Gbely', 'psc' => '90845', 'krajina' => 'Slovensko'],
        ['mesto' => 'Stupava', 'psc' => '90031', 'krajina' => 'Slovensko'],
        ['mesto' => 'Svätý Jur', 'psc' => '90021', 'krajina' => 'Slovensko'],
        ['mesto' => 'Modra', 'psc' => '90201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Svätý Martin', 'psc' => '03601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rajec', 'psc' => '01512', 'krajina' => 'Slovensko'],
        ['mesto' => 'Krásno nad Kysucou', 'psc' => '02302', 'krajina' => 'Slovensko'],
        ['mesto' => 'Turzovka', 'psc' => '02353', 'krajina' => 'Slovensko'],
        ['mesto' => 'Cadca', 'psc' => '02201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Oščadnica', 'psc' => '02354', 'krajina' => 'Slovensko'],
        ['mesto' => 'Terchová', 'psc' => '01306', 'krajina' => 'Slovensko'],
        ['mesto' => 'Varín', 'psc' => '01303', 'krajina' => 'Slovensko'],
        ['mesto' => 'Strečno', 'psc' => '01305', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vrútky', 'psc' => '03861', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kláštor pod Znievom', 'psc' => '03852', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kremnica', 'psc' => '96701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nová Baňa', 'psc' => '96801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Žarnovica', 'psc' => '96601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tlmače', 'psc' => '93501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šurany', 'psc' => '94201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Hurbanovo', 'psc' => '94701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kolárovo', 'psc' => '94602', 'krajina' => 'Slovensko'],
        ['mesto' => 'Moldava nad Bodvou', 'psc' => '04501', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rožňava', 'psc' => '04801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dobšiná', 'psc' => '04925', 'krajina' => 'Slovensko'],
        ['mesto' => 'Košice-Juh', 'psc' => '04011', 'krajina' => 'Slovensko'],
        ['mesto' => 'Košice-Sever', 'psc' => '04017', 'krajina' => 'Slovensko'],
        ['mesto' => 'Košice-Západ', 'psc' => '04001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišské Vlachy', 'psc' => '05361', 'krajina' => 'Slovensko'],
        ['mesto' => 'Krompachy', 'psc' => '05342', 'krajina' => 'Slovensko'],
        ['mesto' => 'Smižany', 'psc' => '05201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišská Stará Ves', 'psc' => '06101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Podolínec', 'psc' => '06503', 'krajina' => 'Slovensko'],
        ['mesto' => 'Hrhov', 'psc' => '04934', 'krajina' => 'Slovensko'],
        ['mesto' => 'Štítnik', 'psc' => '04923', 'krajina' => 'Slovensko'],
        ['mesto' => 'Plešivec', 'psc' => '04911', 'krajina' => 'Slovensko'],
        ['mesto' => 'Jelšava', 'psc' => '09801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Muráň', 'psc' => '05062', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tisovec', 'psc' => '98061', 'krajina' => 'Slovensko'],
        ['mesto' => 'Hnúšťa', 'psc' => '98101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kalinovo', 'psc' => '98901', 'krajina' => 'Slovensko'],
        ['mesto' => 'Divín', 'psc' => '98532', 'krajina' => 'Slovensko'],
        ['mesto' => 'Modrý Kameň', 'psc' => '99103', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šahy', 'psc' => '93601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Želiezovce', 'psc' => '93701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kálnica', 'psc' => '95614', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bánovce nad Bebravou', 'psc' => '95701', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bojnice', 'psc' => '97201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Handlová', 'psc' => '97251', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nováky', 'psc' => '97271', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zemianske Kostoľany', 'psc' => '97243', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nedožery-Brezany', 'psc' => '97201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dubnica nad Váhom', 'psc' => '01841', 'krajina' => 'Slovensko'],
        ['mesto' => 'Lednické Rovne', 'psc' => '02061', 'krajina' => 'Slovensko'],
        ['mesto' => 'Beluša', 'psc' => '01861', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ladce', 'psc' => '01863', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nemšová', 'psc' => '91441', 'krajina' => 'Slovensko'],
        ['mesto' => 'Stará Turá', 'psc' => '91601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bošáca', 'psc' => '91656', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vrbové', 'psc' => '92203', 'krajina' => 'Slovensko'],
        ['mesto' => 'Leopoldov', 'psc' => '92041', 'krajina' => 'Slovensko'],
        ['mesto' => 'Červeník', 'psc' => '92024', 'krajina' => 'Slovensko'],
        ['mesto' => 'Smolenice', 'psc' => '91904', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dolná Streda', 'psc' => '92527', 'krajina' => 'Slovensko'],
        ['mesto' => 'Sereď', 'psc' => '92601', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šintava', 'psc' => '92531', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vlčkovce', 'psc' => '91951', 'krajina' => 'Slovensko'],
        ['mesto' => 'Veľká Mača', 'psc' => '92538', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šoporňa', 'psc' => '92527', 'krajina' => 'Slovensko'],
        ['mesto' => 'Neded', 'psc' => '92534', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šulekovo', 'psc' => '92101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zbehy', 'psc' => '95137', 'krajina' => 'Slovensko'],
        ['mesto' => 'Cabaj-Čápor', 'psc' => '95117', 'krajina' => 'Slovensko'],
        ['mesto' => 'Štitáre', 'psc' => '95114', 'krajina' => 'Slovensko'],
        ['mesto' => 'Veľké Zálužie', 'psc' => '95107', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ivanka pri Nitre', 'psc' => '95112', 'krajina' => 'Slovensko'],
        ['mesto' => 'Jelka', 'psc' => '92523', 'krajina' => 'Slovensko'],
        ['mesto' => 'Veľký Meder', 'psc' => '93201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Gabčíkovo', 'psc' => '93005', 'krajina' => 'Slovensko'],
        ['mesto' => 'Šamorín', 'psc' => '93101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kalinkovo', 'psc' => '90010', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rovinka', 'psc' => '90041', 'krajina' => 'Slovensko'],
        ['mesto' => 'Záhorská Bystrica', 'psc' => '84106', 'krajina' => 'Slovensko'],
        ['mesto' => 'Devínska Nová Ves', 'psc' => '84107', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rača', 'psc' => '83106', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vajnory', 'psc' => '83107', 'krajina' => 'Slovensko'],
        ['mesto' => 'Podunajské Biskupice', 'psc' => '82106', 'krajina' => 'Slovensko'],
        ['mesto' => 'Petržalka', 'psc' => '85101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Rusovce', 'psc' => '85110', 'krajina' => 'Slovensko'],
        ['mesto' => 'Jarovce', 'psc' => '85110', 'krajina' => 'Slovensko'],
        ['mesto' => 'Čunovo', 'psc' => '85110', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vrakuňa', 'psc' => '82107', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ružinov', 'psc' => '82101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nové Mesto', 'psc' => '83101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Dúbravka', 'psc' => '84101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Lamač', 'psc' => '84103', 'krajina' => 'Slovensko'],
        ['mesto' => 'Záhorská Bystrica', 'psc' => '84106', 'krajina' => 'Slovensko'],
        ['mesto' => 'Karlova Ves', 'psc' => '84104', 'krajina' => 'Slovensko'],
        ['mesto' => 'Staré Mesto', 'psc' => '81101', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ľubica', 'psc' => '06001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vrbov', 'psc' => '05973', 'krajina' => 'Slovensko'],
        ['mesto' => 'Spišská Teplica', 'psc' => '05914', 'krajina' => 'Slovensko'],
        ['mesto' => 'Vikartovce', 'psc' => '05926', 'krajina' => 'Slovensko'],
        ['mesto' => 'Štrba', 'psc' => '05978', 'krajina' => 'Slovensko'],
        ['mesto' => 'Štrbské Pleso', 'psc' => '05985', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tatranská Lomnica', 'psc' => '05960', 'krajina' => 'Slovensko'],
        ['mesto' => 'Starý Smokovec', 'psc' => '06201', 'krajina' => 'Slovensko'],
        ['mesto' => 'Tatranská Kotlina', 'psc' => '06001', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zdiar', 'psc' => '05955', 'krajina' => 'Slovensko'],
        ['mesto' => 'Ždiar', 'psc' => '05955', 'krajina' => 'Slovensko'],
        ['mesto' => 'Liptovský Hrádok', 'psc' => '03301', 'krajina' => 'Slovensko'],
        ['mesto' => 'Závažná Poruba', 'psc' => '03215', 'krajina' => 'Slovensko'],
        ['mesto' => 'Pribylina', 'psc' => '03242', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bobrovec', 'psc' => '03221', 'krajina' => 'Slovensko'],
        ['mesto' => 'Kvačany', 'psc' => '02744', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zuberec', 'psc' => '02744', 'krajina' => 'Slovensko'],
        ['mesto' => 'Habovka', 'psc' => '02744', 'krajina' => 'Slovensko'],
        ['mesto' => 'Oravský Podzámok', 'psc' => '02741', 'krajina' => 'Slovensko'],
        ['mesto' => 'Oravská Lesná', 'psc' => '02973', 'krajina' => 'Slovensko'],
        ['mesto' => 'Zákamenné', 'psc' => '02956', 'krajina' => 'Slovensko'],
        ['mesto' => 'Nižná', 'psc' => '02751', 'krajina' => 'Slovensko'],
        ['mesto' => 'Trstená', 'psc' => '02801', 'krajina' => 'Slovensko'],
        ['mesto' => 'Bobrov', 'psc' => '02921', 'krajina' => 'Slovensko'],
        ['mesto' => 'Praha', 'psc' => '11000', 'krajina' => 'Česko'],
        ['mesto' => 'Brno', 'psc' => '60200', 'krajina' => 'Česko'],
        ['mesto' => 'Ostrava', 'psc' => '70200', 'krajina' => 'Česko'],
        ['mesto' => 'Plzeň', 'psc' => '30100', 'krajina' => 'Česko'],
        ['mesto' => 'Liberec', 'psc' => '46001', 'krajina' => 'Česko'],
        ['mesto' => 'Olomouc', 'psc' => '77900', 'krajina' => 'Česko'],
        ['mesto' => 'České Budějovice', 'psc' => '37001', 'krajina' => 'Česko'],
        ['mesto' => 'Hradec Králové', 'psc' => '50002', 'krajina' => 'Česko'],
        ['mesto' => 'Ústí nad Labem', 'psc' => '40001', 'krajina' => 'Česko'],
        ['mesto' => 'Pardubice', 'psc' => '53002', 'krajina' => 'Česko'],
        ['mesto' => 'Zlín', 'psc' => '76001', 'krajina' => 'Česko'],
        ['mesto' => 'Havířov', 'psc' => '73601', 'krajina' => 'Česko'],
        ['mesto' => 'Kladno', 'psc' => '27201', 'krajina' => 'Česko'],
        ['mesto' => 'Most', 'psc' => '43401', 'krajina' => 'Česko'],
        ['mesto' => 'Opava', 'psc' => '74601', 'krajina' => 'Česko'],
        ['mesto' => 'Frýdek-Místek', 'psc' => '73801', 'krajina' => 'Česko'],
        ['mesto' => 'Karviná', 'psc' => '73401', 'krajina' => 'Česko'],
        ['mesto' => 'Jihlava', 'psc' => '58601', 'krajina' => 'Česko'],
        ['mesto' => 'Teplice', 'psc' => '41501', 'krajina' => 'Česko'],
        ['mesto' => 'Děčín', 'psc' => '40502', 'krajina' => 'Česko'],
        ['mesto' => 'Chomutov', 'psc' => '43001', 'krajina' => 'Česko'],
        ['mesto' => 'Přerov', 'psc' => '75002', 'krajina' => 'Česko'],
        ['mesto' => 'Jablonec nad Nisou', 'psc' => '46601', 'krajina' => 'Česko'],
        ['mesto' => 'Prostějov', 'psc' => '79601', 'krajina' => 'Česko'],
        ['mesto' => 'Mladá Boleslav', 'psc' => '29301', 'krajina' => 'Česko'],
        ['mesto' => 'Nový Jičín', 'psc' => '74101', 'krajina' => 'Česko'],
        ['mesto' => 'České Velenice', 'psc' => '37881', 'krajina' => 'Česko'],
        ['mesto' => 'Třinec', 'psc' => '73961', 'krajina' => 'Česko'],
        ['mesto' => 'Znojmo', 'psc' => '66902', 'krajina' => 'Česko'],
        ['mesto' => 'Cheb', 'psc' => '35002', 'krajina' => 'Česko'],
        ['mesto' => 'Kolín', 'psc' => '28002', 'krajina' => 'Česko'],
        ['mesto' => 'Příbram', 'psc' => '26101', 'krajina' => 'Česko'],
        ['mesto' => 'Trutnov', 'psc' => '54101', 'krajina' => 'Česko'],
        ['mesto' => 'Beroun', 'psc' => '26601', 'krajina' => 'Česko'],
        ['mesto' => 'Třebíč', 'psc' => '67401', 'krajina' => 'Česko'],
        ['mesto' => 'Šumperk', 'psc' => '78701', 'krajina' => 'Česko'],
        ['mesto' => 'Kroměříž', 'psc' => '76701', 'krajina' => 'Česko'],
        ['mesto' => 'Uherské Hradiště', 'psc' => '68601', 'krajina' => 'Česko'],
        ['mesto' => 'Vsetín', 'psc' => '75501', 'krajina' => 'Česko'],
        ['mesto' => 'Litoměřice', 'psc' => '41201', 'krajina' => 'Česko'],
        ['mesto' => 'Sokolov', 'psc' => '35601', 'krajina' => 'Česko'],
        ['mesto' => 'Česká Lípa', 'psc' => '47001', 'krajina' => 'Česko'],
        ['mesto' => 'Karviná-Mizerov', 'psc' => '73401', 'krajina' => 'Česko'],
        ['mesto' => 'Bohumín', 'psc' => '73581', 'krajina' => 'Česko'],
        ['mesto' => 'Kopřivnice', 'psc' => '74221', 'krajina' => 'Česko'],
        ['mesto' => 'Kutná Hora', 'psc' => '28401', 'krajina' => 'Česko'],
        ['mesto' => 'Blansko', 'psc' => '67801', 'krajina' => 'Česko'],
        ['mesto' => 'Hodonín', 'psc' => '69501', 'krajina' => 'Česko'],
        ['mesto' => 'Strakonice', 'psc' => '38601', 'krajina' => 'Česko'],
        ['mesto' => 'Písek', 'psc' => '39701', 'krajina' => 'Česko'],
        ['mesto' => 'Rychnov nad Kněžnou', 'psc' => '51601', 'krajina' => 'Česko'],
        ['mesto' => 'Náchod', 'psc' => '54701', 'krajina' => 'Česko'],
        ['mesto' => 'Havlíčkův Brod', 'psc' => '58001', 'krajina' => 'Česko'],
        ['mesto' => 'Žďár nad Sázavou', 'psc' => '59101', 'krajina' => 'Česko'],
        ['mesto' => 'Velké Meziříčí', 'psc' => '59401', 'krajina' => 'Česko'],
        ['mesto' => 'Uherský Brod', 'psc' => '68801', 'krajina' => 'Česko'],
        ['mesto' => 'Vyškov', 'psc' => '68201', 'krajina' => 'Česko'],
        ['mesto' => 'Svitavy', 'psc' => '56802', 'krajina' => 'Česko'],
        ['mesto' => 'Ústí nad Orlicí', 'psc' => '56201', 'krajina' => 'Česko'],
        ['mesto' => 'Chrudim', 'psc' => '53701', 'krajina' => 'Česko'],
        ['mesto' => 'Klatovy', 'psc' => '33901', 'krajina' => 'Česko'],
        ['mesto' => 'Domažlice', 'psc' => '34401', 'krajina' => 'Česko'],
        ['mesto' => 'Tábor', 'psc' => '39001', 'krajina' => 'Česko'],
        ['mesto' => 'Jindřichův Hradec', 'psc' => '37701', 'krajina' => 'Česko'],
        ['mesto' => 'Pelhřimov', 'psc' => '39301', 'krajina' => 'Česko'],
        ['mesto' => 'Prachatice', 'psc' => '38301', 'krajina' => 'Česko'],
        ['mesto' => 'Český Krumlov', 'psc' => '38101', 'krajina' => 'Česko'],
        ['mesto' => 'Rakovník', 'psc' => '26901', 'krajina' => 'Česko'],
        ['mesto' => 'Mělník', 'psc' => '27601', 'krajina' => 'Česko'],
        ['mesto' => 'Nymburk', 'psc' => '28802', 'krajina' => 'Česko'],
        ['mesto' => 'Brandýs nad Labem', 'psc' => '25001', 'krajina' => 'Česko'],
        ['mesto' => 'Benešov', 'psc' => '25601', 'krajina' => 'Česko'],
        ['mesto' => 'Příbor', 'psc' => '74258', 'krajina' => 'Česko'],
        ['mesto' => 'Bílovec', 'psc' => '74301', 'krajina' => 'Česko'],
        ['mesto' => 'Frenštát pod Radhoštěm', 'psc' => '74411', 'krajina' => 'Česko'],
        ['mesto' => 'Rožnov pod Radhoštěm', 'psc' => '75661', 'krajina' => 'Česko'],
        ['mesto' => 'Valašské Meziříčí', 'psc' => '75701', 'krajina' => 'Česko'],
        ['mesto' => 'Valašské Klobouky', 'psc' => '76601', 'krajina' => 'Česko'],
        ['mesto' => 'Luhačovice', 'psc' => '76326', 'krajina' => 'Česko'],
        ['mesto' => 'Otrokovice', 'psc' => '76502', 'krajina' => 'Česko'],
        ['mesto' => 'Holešov', 'psc' => '76901', 'krajina' => 'Česko'],
        ['mesto' => 'Bystřice pod Hostýnem', 'psc' => '76861', 'krajina' => 'Česko'],
        ['mesto' => 'Hulín', 'psc' => '76824', 'krajina' => 'Česko'],
        ['mesto' => 'Litvínov', 'psc' => '43601', 'krajina' => 'Česko'],
        ['mesto' => 'Kadaň', 'psc' => '43201', 'krajina' => 'Česko'],
        ['mesto' => 'Louny', 'psc' => '44001', 'krajina' => 'Česko'],
        ['mesto' => 'Žatec', 'psc' => '43801', 'krajina' => 'Česko'],
        ['mesto' => 'Podbořany', 'psc' => '44101', 'krajina' => 'Česko'],
        ['mesto' => 'Lovosice', 'psc' => '41002', 'krajina' => 'Česko'],
        ['mesto' => 'Roudnice nad Labem', 'psc' => '41301', 'krajina' => 'Česko'],
        ['mesto' => 'Česká Kamenice', 'psc' => '40721', 'krajina' => 'Česko'],
        ['mesto' => 'Rumburk', 'psc' => '40801', 'krajina' => 'Česko'],
        ['mesto' => 'Varnsdorf', 'psc' => '40747', 'krajina' => 'Česko'],
        ['mesto' => 'Nový Bor', 'psc' => '47301', 'krajina' => 'Česko'],
        ['mesto' => 'Turnov', 'psc' => '51101', 'krajina' => 'Česko'],
        ['mesto' => 'Semily', 'psc' => '51301', 'krajina' => 'Česko'],
        ['mesto' => 'Rokytnice nad Jizerou', 'psc' => '51244', 'krajina' => 'Česko'],
        ['mesto' => 'Tanvald', 'psc' => '46841', 'krajina' => 'Česko'],
        ['mesto' => 'Warszawa', 'psc' => '00-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Kraków', 'psc' => '30-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Łódź', 'psc' => '90-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Wrocław', 'psc' => '50-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Poznań', 'psc' => '60-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Gdańsk', 'psc' => '80-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Szczecin', 'psc' => '70-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Bydgoszcz', 'psc' => '85-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Lublin', 'psc' => '20-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Katowice', 'psc' => '40-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Białystok', 'psc' => '15-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Gdynia', 'psc' => '81-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Częstochowa', 'psc' => '42-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Radom', 'psc' => '26-600', 'krajina' => 'Poľsko'],
        ['mesto' => 'Sosnowiec', 'psc' => '41-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Toruń', 'psc' => '87-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Kielce', 'psc' => '25-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Rzeszów', 'psc' => '35-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Gliwice', 'psc' => '44-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zabrze', 'psc' => '41-800', 'krajina' => 'Poľsko'],
        ['mesto' => 'Olsztyn', 'psc' => '10-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Bielsko-Biała', 'psc' => '43-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Bytom', 'psc' => '41-902', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zielona Góra', 'psc' => '65-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Rybnik', 'psc' => '44-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Ruda Śląska', 'psc' => '41-700', 'krajina' => 'Poľsko'],
        ['mesto' => 'Opole', 'psc' => '45-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Tychy', 'psc' => '43-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Gorzów Wielkopolski', 'psc' => '66-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Dąbrowa Górnicza', 'psc' => '41-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Elbląg', 'psc' => '82-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Płock', 'psc' => '09-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Wałbrzych', 'psc' => '58-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Włocławek', 'psc' => '87-800', 'krajina' => 'Poľsko'],
        ['mesto' => 'Tarnów', 'psc' => '33-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Chorzów', 'psc' => '41-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Koszalin', 'psc' => '75-001', 'krajina' => 'Poľsko'],
        ['mesto' => 'Kalisz', 'psc' => '62-800', 'krajina' => 'Poľsko'],
        ['mesto' => 'Legnica', 'psc' => '59-220', 'krajina' => 'Poľsko'],
        ['mesto' => 'Grudziądz', 'psc' => '86-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Jaworzno', 'psc' => '43-600', 'krajina' => 'Poľsko'],
        ['mesto' => 'Jastrzębie-Zdrój', 'psc' => '44-330', 'krajina' => 'Poľsko'],
        ['mesto' => 'Nowy Sącz', 'psc' => '33-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Jelenia Góra', 'psc' => '58-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Siedlce', 'psc' => '08-110', 'krajina' => 'Poľsko'],
        ['mesto' => 'Mysłowice', 'psc' => '41-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Konin', 'psc' => '62-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Piotrków Trybunalski', 'psc' => '97-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Inowrocław', 'psc' => '88-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Lubin', 'psc' => '59-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Ostrów Wielkopolski', 'psc' => '63-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Suwałki', 'psc' => '16-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Gniezno', 'psc' => '62-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Ostrowiec Świętokrzyski', 'psc' => '27-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Stargard', 'psc' => '73-110', 'krajina' => 'Poľsko'],
        ['mesto' => 'Siemianowice Śląskie', 'psc' => '41-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Pabianice', 'psc' => '95-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Przemyśl', 'psc' => '37-700', 'krajina' => 'Poľsko'],
        ['mesto' => 'Stalowa Wola', 'psc' => '37-450', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zamość', 'psc' => '22-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zawiercie', 'psc' => '42-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Tomaszów Mazowiecki', 'psc' => '97-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Łomża', 'psc' => '18-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Mielec', 'psc' => '39-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Będzin', 'psc' => '42-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Czeladź', 'psc' => '41-250', 'krajina' => 'Poľsko'],
        ['mesto' => 'Tczew', 'psc' => '83-110', 'krajina' => 'Poľsko'],
        ['mesto' => 'Biała Podlaska', 'psc' => '21-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Leszno', 'psc' => '64-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zgorzelec', 'psc' => '59-900', 'krajina' => 'Poľsko'],
        ['mesto' => 'Świdnica', 'psc' => '58-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Piła', 'psc' => '64-920', 'krajina' => 'Poľsko'],
        ['mesto' => 'Nowy Targ', 'psc' => '34-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Zakopane', 'psc' => '34-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Oświęcim', 'psc' => '32-600', 'krajina' => 'Poľsko'],
        ['mesto' => 'Wadowice', 'psc' => '34-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Żywiec', 'psc' => '34-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Cieszyn', 'psc' => '43-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Czechowice-Dziedzice', 'psc' => '43-502', 'krajina' => 'Poľsko'],
        ['mesto' => 'Żory', 'psc' => '44-240', 'krajina' => 'Poľsko'],
        ['mesto' => 'Racibórz', 'psc' => '47-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Wodzisław Śląski', 'psc' => '44-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Tarnowskie Góry', 'psc' => '42-600', 'krajina' => 'Poľsko'],
        ['mesto' => 'Świętochłowice', 'psc' => '41-600', 'krajina' => 'Poľsko'],
        ['mesto' => 'Piekary Śląskie', 'psc' => '41-940', 'krajina' => 'Poľsko'],
        ['mesto' => 'Mikołów', 'psc' => '43-190', 'krajina' => 'Poľsko'],
        ['mesto' => 'Knurów', 'psc' => '44-190', 'krajina' => 'Poľsko'],
        ['mesto' => 'Myszkow', 'psc' => '42-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Ostrów Mazowiecka', 'psc' => '07-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Ciechanów', 'psc' => '06-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Legionowo', 'psc' => '05-120', 'krajina' => 'Poľsko'],
        ['mesto' => 'Pruszków', 'psc' => '05-800', 'krajina' => 'Poľsko'],
        ['mesto' => 'Piaseczno', 'psc' => '05-500', 'krajina' => 'Poľsko'],
        ['mesto' => 'Wołomin', 'psc' => '05-200', 'krajina' => 'Poľsko'],
        ['mesto' => 'Mińsk Mazowiecki', 'psc' => '05-300', 'krajina' => 'Poľsko'],
        ['mesto' => 'Otwock', 'psc' => '05-400', 'krajina' => 'Poľsko'],
        ['mesto' => 'Nowy Dwór Mazowiecki', 'psc' => '05-100', 'krajina' => 'Poľsko'],
        ['mesto' => 'Żyrardów', 'psc' => '96-300', 'krajina' => 'Poľsko'],
    ]);
    }
}
