<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProduktSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Info a popisy produktov, boli generované pomocou Gemini AI https://gemini.google.com/app 
     */
    public function run(): void
    {
        DB::table('produkty')->insert([
        // Hry (kategoria_id: 1)
        ['kategoria_id' => 1, 'meno' => 'All of Them Part III', 'popis' => 'Tretí diel legendárnej série All of Them.', 'info' => 'Záverečná kapitola trilógie, ktorá definovala žáner moderných adventúr. V All of Them Part III sa opäť stretávame s hlavným hrdinom na jeho ceste za vykúpením v post-apokalyptickom svete, kde hranica medzi dobrom a zlom prakticky neexistuje. Čaká vás viac než 40 hodín herného času, dychberúca grafika optimalizovaná pre novú generáciu konzol a príbeh, ktorý vás nenechá chladnými až do úplného konca. Vaše voľby z predchádzajúcich dielov (ak máte uložené pozície) priamo ovplyvnia začiatok tejto hry.', 'obrazok' => 'AllOfThemIII.webp', 'cena' => 59.99, 'doplnkove_info' => 'PS6, PC', 'pocet_na_sklade' => 25, 'hodnotenie' => 4.8, 'typ' => 'Adventúra'],
        ['kategoria_id' => 1, 'meno' => 'CyberBug 2067', 'popis' => 'Futuristická RPG hra v otvorenom svete.', 'info' => 'Vitajte v Neon City, metropole, kde technológia znamená moc a ľudský život nemá žiadnu cenu. CyberBug 2067 je ambiciózne RPG, ktoré vám umožní plne si prispôsobiť svoje kybernetické telo a vybrať si vlastnú cestu podsvetím. Či už sa rozhodnete byť tichým hackerom, alebo brutálnym žoldnierom s oceľovými päsťami, mesto reaguje na každý váš krok. Hra obsahuje prepracovaný systém vzťahov, dynamické striedanie dňa a noci a stovky vedľajších úloh, ktoré rozširujú bohatý lore tohto temného sveta.', 'cena' => 54.99, 'obrazok' => 'CyberBug.webp', 'doplnkove_info' => 'PC, PS6, PS7', 'pocet_na_sklade' => 40, 'hodnotenie' => 4.3, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'Megaboing', 'popis' => 'Zábavná plošinovka pre celú rodinu.', 'info' => 'Pripravte sa na najväčšie skákacie dobrodružstvo roka! Megaboing prináša klasickú hrateľnosť v modernom 4K šate. Prechádzajte cez farebné svety, zbierajte zlaté pružiny a porazte zlého Doktora Gravitáciu, ktorý chce zastaviť všetko poskakovanie na svete. Hra ponúka lokálny kooperatívny režim až pre 4 hráčov, čo z nej robí ideálny titul na rodinné večery alebo párty s priateľmi. Obsahuje viac ako 100 unikátnych levelov a odomykateľné kostýmy pre vašu postavičku.', 'cena' => 39.99, 'obrazok' => 'megaboing.webp', 'doplnkove_info' => 'PC, PS6, PS7', 'pocet_na_sklade' => 60, 'hodnotenie' => 4.6, 'typ' => 'Akčné'],
        ['kategoria_id' => 1, 'meno' => 'My Meowing Cats', 'popis' => 'Relaxačná simulácia so mačkami.', 'info' => 'Potrebujete si oddýchnuť po náročnom dni? My Meowing Cats je dokonalý digitálny azyl. Adoptujte si virtuálne mačiatka, starajte sa o ne, zariaďujte im ich vlastný mačací hotel a sledujte ich realistické správanie poháňané pokročilou AI. Každá mačka má svoju vlastnú osobnosť a potreby. Hra využíva haptickú odozvu ovládačov, takže pri hladkaní budete cítiť skutočné pradenie. Neobsahuje žiadny stres, žiadne mikrotransakcie, len čistú radosť z prítomnosti chlpatých spoločníkov.', 'cena' => 19.99, 'obrazok' => 'MyMeowingCats.webp', 'doplnkove_info' => 'PC, PS6', 'pocet_na_sklade' => 80, 'hodnotenie' => 4.5, 'typ' => 'Simulátor'],
        ['kategoria_id' => 1, 'meno' => 'Path of Fiitkar', 'popis' => 'Epická fantasy akčná RPG.', 'info' => 'Vstúpte do sveta Fiitkar, krajiny rozmanitých kultúr a prastarých bohov, ktorí sa prebudili z tisícročného spánku. Ako vyvolený bojovník musíte zjednotiť rozhádané klany a postaviť sa hrozbe, ktorá prichádza z tieňov. Path of Fiitkar kombinuje náročný súbojový systém založený na načasovaní s hlbokým stromom schopností, ktorý umožňuje tisíce kombinácií kúziel a útokov. Objavujte skryté dungeony, bojujte s gigantickými bossmi a staňte sa legendou, o ktorej sa budú spievať piesne pri krbe.', 'cena' => 49.99, 'obrazok' => 'PathOfFiitkar.webp', 'doplnkove_info' => 'PC, PS6, PS7', 'pocet_na_sklade' => 35, 'hodnotenie' => 4.7, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'The Wichter: The Legend of Regalt', 'popis' => 'Rozsiahla RPG hra s bohatým príbehom.', 'info' => 'Regalt z Virie nebol vždy legendou. Bol to muž s mečom, dlhmi a príliš veľa nepriateľmi. V tejto epickej RPG hre prežiješ jeho príbeh od začiatku - od prvého zabitého monštra až po okamih, keď celý svet začal šepkať jeho meno. Preskúmaj rozľahlý otvorený svet plný živých miest, zabudnutých ruín a stvorení, ktoré ťa nepustia spať. Každé rozhodnutie má cenu. Každý spojenec môže byť zrada. A každý súboj môže byť posledný.', 'cena' => 49.99, 'obrazok' => 'TheWichter.webp', 'doplnkove_info' => 'PC, PS6, PS7', 'pocet_na_sklade' => 50, 'hodnotenie' => 4.9, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'Football 26', 'popis' => 'Moderná futbalová hra s pokročilými technikami a rýchlonaučiteľným formátom.', 'info' => 'Football 26 prináša revolúciu v športových simulátoroch vďaka technológii RealMotion 3.0, ktorá sníma pohyby hráčov v reálnom čase priamo z trávnika. Vychutnajte si vylepšený režim kariéry, kde manažujete nielen tím na ihrisku, ale aj vzťahy s fanúšikmi a sponzormi. Nový "Rýchly Formát" umožňuje odohrať intenzívny zápas v priebehu 5 minút, čo je ideálne pre zaneprázdnených hráčov. Kompletne licencované ligy, realistická fyzika lopty a atmosféra, pri ktorej budete mať pocit, že sedíte priamo na štadióne.', 'cena' => 59.99, 'obrazok' => 'football26.webp', 'doplnkove_info' => 'PC, PS6, PS7', 'pocet_na_sklade' => 50, 'hodnotenie' => 4.3, 'typ' => 'Športové'],
        
        // Konzoly (kategoria_id: 2)
        ['kategoria_id' => 2, 'meno' => 'PlayState 6', 'popis' => 'Výkonná herná konzola 6. generácie.', 'info' => 'PlayState 6 prináša novú éru domácej zábavy s bleskovým 1TB SSD diskom, ktorý prakticky eliminuje načítavacie obrazovky. Vďaka plnej podpore 4K rozlíšenia a HDR technológii zažijete hry s neuveriteľnými detailmi a vernými farbami. Nový ovládač StateSense ponúka adaptívne spúšte a vylepšenú haptickú odozvu, ktorá vás vtiahne priamo do centra diania, či už cítite odpor luku alebo vibrácie motora.', 'cena' => 499.99, 'obrazok' => 'PS6.webp', 'doplnkove_info' => '1TB SSD, 4K HDR', 'pocet_na_sklade' => 15, 'hodnotenie' => 4.8, 'typ' => 'K TV'],
        ['kategoria_id' => 2, 'meno' => 'PlayState 7', 'popis' => 'Najnovšia herná konzola s 8K podporou.', 'info' => 'Budúcnosť je tu. PlayState 7 posúva hranice možného s masívnym výkonom určeným pre natívne 8K hranie a ray-tracing druhej generácie. S 2TB ultra-rýchlym úložiskom máte dostatok miesta na celú knižnicu AAA titulov. Konzola je navrhnutá pre najnáročnejších hráčov, ktorí vyžadujú stabilných 120 FPS a nekompromisnú vizuálnu kvalitu. Elegantný dizajn s tichým chladením zapadne do každej modernej obývačky.', 'cena' => 649.99, 'obrazok' => 'PS7.webp', 'doplnkove_info' => '2TB SSD, 8K HDR', 'pocet_na_sklade' => 10, 'hodnotenie' => 4.9, 'typ' => 'Moderné'],
        ['kategoria_id' => 2, 'meno' => 'Ybox 180', 'popis' => 'Výkonná herná konzola od Ybox so stálou podporou', 'info' => 'Ybox 180 je spoľahlivým centrom vašej domácej zábavy. Ponúka vyvážený pomer ceny a výkonu s plnou podporou ekosystému Ybox Live. Vďaka funkcii Quick Resume môžete okamžite prepínať medzi viacerými rozohranými hrami bez čakania. Integrovaný 1TB SSD disk a podpora 4K HDR zaručujú, že všetky vaše obľúbené tituly budú vyzerať a hýbať sa lepšie než kedykoľvek predtým.', 'cena' => 479.99, 'obrazok' => 'Ybox180.webp', 'doplnkove_info' => '1TB SSD, 4K HDR', 'pocet_na_sklade' => 22, 'hodnotenie' => 4.9, 'typ' => 'K TV'],
        ['kategoria_id' => 2, 'meno' => 'Ybox Series M', 'popis' => 'Najmodernejšia herná konzola s až 8K podporou.', 'info' => 'Vlajková loď rodiny Ybox. Series M je beštia ukrytá v minimalistickom tele, ktorá cieli na najvyššiu možnú vernosť obrazu a zvuku. S podporou 8K rozlíšenia a priestorového audia Dolby Atmos vás hry úplne pohltia. Obrovské 2TB SSD úložisko a špeciálna architektúra spracovania dát umožňujú vývojárom vytvárať svety bez limitov. Ideálna voľba pre hráčov, ktorí chcú mať to najlepšie na trhu.', 'cena' => 659.99, 'obrazok' => 'YboxSeriesM.webp', 'doplnkove_info' => '2TB SSD, 8K HDR', 'pocet_na_sklade' => 9, 'hodnotenie' => 4.6, 'typ' => 'Moderné'],
        ['kategoria_id' => 2, 'meno' => 'GameGirl', 'popis' => 'Retro konzola určená pre nežnejšie pokolenie so zábavnými hrami.', 'info' => 'Štýlová, kompaktná a plná nostalgie. GameGirl je navrhnutá s dôrazom na estetiku a jednoduchosť používania. Obsahuje predinštalovanú kolekciu klasických 2D titulov a logických hier, ktoré zabavia na cestách aj doma. Napriek svojmu retro zameraniu disponuje Full HD displejom a 256GB úložiskom, čo z nej robí moderný kúsok histórie v ružových a pastelových tónoch. Skvelý darček pre každú hráčku.', 'cena' => 79.99, 'obrazok' => 'gamegirl.webp', 'doplnkove_info' => '256GB HDD, FULL HD', 'pocet_na_sklade' => 22, 'hodnotenie' => 4.5, 'typ' => 'HandHeld'],
        ['kategoria_id' => 2, 'meno' => 'GameGirl Pro', 'popis' => 'Výkonnejšia konzola pre ženy s modernejšími hrami.', 'info' => 'Model Pro posúva zážitok z GameGirl na novú úroveň. S vylepšeným 2K HDR displejom a rýchlym 512GB SSD diskom zvládne aj náročnejšie moderné tituly a simulátory. Ergonomický dizajn prispôsobený menším rukám zaručuje komfort aj pri dlhých hodinách hrania. Konzola podporuje online multiplayer a prichádza s exkluzívnym prístupom k prémiovým titulom v rámci digitálneho obchodu GameGirl Store.', 'cena' => 199.99, 'obrazok' => 'GameGirlPro.webp', 'doplnkove_info' => '512GB SSD, 2K HDR', 'pocet_na_sklade' => 11, 'hodnotenie' => 4.8, 'typ' => 'HandHeld'],
        ['kategoria_id' => 2, 'meno' => 'Steak Deck', 'popis' => 'Najvýkonnejšia Konzola pre hranie na cestách', 'info' => 'Steak Deck je vreckový počítač s nekompromisným výkonom, ktorý vám umožní hrať vašu celú knižnicu z PC kdekoľvek na svete. S 1024GB SSD diskom máte dostatok miesta na tie najväčšie tituly. Vďaka prispôsobiteľným ovládacím prvkom, trackpadom a gyroskopu máte nad hrou rovnakú kontrolu ako pri klávesnici a myši. Jasný Full HD displej a optimalizovaný operačný systém robia z tejto konzoly kráľa handheldov.', 'cena' => 349.99, 'obrazok' => 'SteakDeck.webp', 'doplnkove_info' => '1024GB SSD, Full HD', 'pocet_na_sklade' => 6, 'hodnotenie' => 5, 'typ' => 'HandHeld'],
        ['kategoria_id' => 2, 'meno' => '5SD', 'popis' => 'Retro konzola pre hranie retro hier', 'info' => 'Vráťte sa v čase s konzolou 5SD, ktorá vzdáva hold ére legendárnych vyklápačiek. Táto kompaktná retro mašina je vybavená dvoma displejmi a špeciálnym emulačným čipom, ktorý verným spôsobom reprodukuje hry z 90. a nultých rokov. 128GB úložisko je predplnené stovkami legálnych klasík. Ide o perfektný kúsok pre zberateľov a fanúšikov pixel artu, ktorí chcú mať svoje obľúbené detstvo opäť vo vrecku.', 'cena' => 99.99, 'obrazok' => '5SD.webp', 'doplnkove_info' => '128GB SSD, HD', 'pocet_na_sklade' => 3, 'hodnotenie' => 3.6, 'typ' => 'Retro'],
        ['kategoria_id' => 2, 'meno' => 'Nontend', 'popis' => 'Retro konzola pre hranie Mioro a Ligiui hier', 'info' => 'Nontend je nostalgická krabička k TV, ktorá vás prenesie do zlatej éry 16-bitového hrania. Hoci má hodnotenie u kritikov nízke kvôli svojej svojskej interpretácii známych postáv, fanúšikovia kultových hier o inštalatéroch Miorovi a Ligiuim si prídu na svoje. Podporuje pripojenie dvoch ovládačov pre lokálny súboj a vďaka 256GB SSD disku dokáže bleskovo spúšťať tisíce emulovaných romiek. Je to bizarný, ale milovaný kúsok hardvéru pre skutočných fajnšmekrov.', 'cena' => 149.99, 'obrazok' => 'Nontend.webp', 'doplnkove_info' => '256GB SSD, Full HD', 'pocet_na_sklade' => 5, 'hodnotenie' => 0.8, 'typ' => 'Retro'],
        
        // Merch (kategoria_id: 3)
        ['kategoria_id' => 3, 'meno' => 'Šiltovka Path of Fiitkar', 'popis' => 'Oficiálna šiltovka hry Path of Fiitkar.', 'info' => 'Ukážte svoju príslušnosť k svetu Fiitkar s touto štýlovou šiltovkou. Vyrobená z kvalitnej, priedušnej bavlny s precízne vyšitým logom hry na čelnej strane. Šiltovka má nastaviteľný pásik v zadnej časti, takže sadne každému dobrodruhovi. Ideálny doplnok pre letné dni alebo ako zberateľský kúsok pre každého fanúšika tejto epickej fantasy ságy.', 'cena' => 24.99, 'obrazok' => 'Cap2POF.webp', 'doplnkove_info' => 'Univerzálna veľkosť', 'pocet_na_sklade' => 100, 'hodnotenie' => 4.4, 'typ' => 'Oblečenie'],
        ['kategoria_id' => 3, 'meno' => 'Fanúšikovská šiltovka Path of Fiitkar', 'popis' => 'Limitovaná fanúšikovská edícia šiltovky.', 'info' => 'Špeciálna edícia určená pre tých najvernejších fanúšikov. Táto verzia sa vyznačuje unikátnym farebným prevedením a diskrétnym symbolom na bočnej strane, ktorý odkazuje na skryté mechaniky v hre. Šiltovka je nielen módnym doplnkom, ale aj symbolom komunity, ktorá okolo Path of Fiitkar vznikla. Limitovaný počet kusov zaručuje, že na ulici len tak niekoho s rovnakým kúskom nestretnete.', 'cena' => 19.99, 'obrazok' => 'CapPOF.webp', 'doplnkove_info' => 'Univerzálna veľkosť', 'pocet_na_sklade' => 75, 'hodnotenie' => 4.2, 'typ' => 'Oblečenie'],
        ['kategoria_id' => 3, 'meno' => 'Hrnček Megaboing', 'popis' => 'Keramický hrnček s motívom hry Megaboing.', 'info' => 'Vychutnajte si svoju rannú kávu alebo čaj z hrnčeka, ktorý vám pripomenie vaše obľúbené skákačky. Hrnček je vyrobený z odolnej keramiky a potlačený vysokokvalitným motívom z hry Megaboing, ktorý vydrží aj opakované umývanie v umývačke riadu. Veselý dizajn s Vladom okamžite rozjasní váš pracovný stôl a dodá vám energiu do ďalšieho levelu.', 'cena' => 14.99, 'obrazok' => 'hrncekMegaboing.webp', 'doplnkove_info' => '330ml', 'pocet_na_sklade' => 120, 'hodnotenie' => 4.5, 'typ' => 'Hrnček'],
        ['kategoria_id' => 3, 'meno' => 'Megabox merchu Megaboing', 'popis' => 'Kolekcia merchandise z hry Megaboing v darčekovej krabici.', 'info' => ' ultimátny balíček pre každého nadšenca Megaboingu! Táto luxusná darčeková krabica obsahuje všetko, čo potrebujete na prežitie dňa v štýle Vlada: exkluzívne tričko s motívom hlavného hrdinu, tematický hrnček a veľkoformátový plagát, ktorý oživí každú herňu. Všetko je zabalené v štýlovom boxe, ktorý môžete následne použiť na odkladanie svojich herných ovládačov alebo príslušenstva. Skvelá hodnota za výbornú cenu.', 'cena' => 79.99, 'obrazok' => 'MerchBoxMegaboing.webp', 'doplnkove_info' => 'Obsahuje tričko, hrnček, plagát', 'pocet_na_sklade' => 30, 'hodnotenie' => 4.7, 'typ' => 'Box'],
        ['kategoria_id' => 3, 'meno' => 'Originálna kľúčenka The Wichter', 'popis' => 'Oficiálna kovová kľúčenka The Wichter.', 'info' => 'Majte ducha Regalta z Virie stále pri sebe. Táto masívna kovová kľúčenka je vernou replikou medailónu, ktorý nosí hlavný hrdina. Je odolná voči poškriabaniu a vďaka pevnému krúžku udrží všetky vaše kľúče pohromade. Detailné spracovanie a autentický vzhľad z nej robia povinnú jazdu pre každého milovníka tohto temného fantasy sveta.', 'cena' => 9.99, 'obrazok' => 'klucenka2Wichter.webp', 'doplnkove_info' => 'Kov, 5cm', 'pocet_na_sklade' => 200, 'hodnotenie' => 4.6, 'typ' => 'Kľúčenka'],
        ['kategoria_id' => 3, 'meno' => 'Prémiová kľúčenka The Wichter', 'popis' => 'Prémiová kľúčenka z pozláteného kovu.', 'info' => 'Pre zberateľov, ktorí hľadajú niečo extra. Táto prémiová verzia kľúčenky The Wichter je potiahnutá tenkou vrstvou 24-karátového zlata, čo jej dodáva luxusný lesk a historickú patinu. Dodáva sa v malej zamatovej krabičke, vďaka čomu je ideálnym darčekom. Každý detail na medailóne bol ručne začistený, aby vynikla hrozivá krása symbolu legendárneho zaklínača.', 'cena' => 19.99, 'obrazok' => 'klucenkaWichter.webp', 'doplnkove_info' => 'Pozlátený kov, 6cm', 'pocet_na_sklade' => 80, 'hodnotenie' => 4.8, 'typ' => 'Kľúčenka'],
        ['kategoria_id' => 3, 'meno' => 'Originálny plagát The Wichter', 'popis' => 'Oficiálny plagát hry The Wichter.', 'info' => 'Premeňte svoju izbu na kúsok Virie. Tento vysokokvalitný plagát na lesklom papieri zobrazuje Regalta v dramatickej póze pred mestskými hradbami. Vďaka veľkosti A2 a precíznej tlači uvidíte každý detail na jeho zbroji aj v pozadí krajiny. Plagát je doručovaný v pevnom tubuse, aby sa predišlo akémukoľvek pokrčeniu počas prepravy.', 'cena' => 12.99, 'obrazok' => 'plagatWichter2.webp', 'doplnkove_info' => 'A2, lesklý papier', 'pocet_na_sklade' => 150, 'hodnotenie' => 4.5, 'typ' => 'Plagát'],
        ['kategoria_id' => 3, 'meno' => 'Fan plagát The Wichter', 'popis' => 'Limitovaný fanúšikovský plagát The Wichter.', 'info' => 'Umeleckejšia verzia plagátu pre fanúšikov s vycibreným vkusom. Tento kúsok na matnom papieri využíva minimalistickú grafiku a siluety, ktoré zachytávajú atmosféru hry bez zbytočného vizuálneho šumu. Matný povrch eliminuje odlesky svetla, takže plagát vyzerá skvele z každého uhla. Skvelý doplnok do moderne zariadenej izby.', 'cena' => 9.99, 'obrazok' => 'plagatWichter.webp', 'doplnkove_info' => 'A3, matný papier', 'pocet_na_sklade' => 200, 'hodnotenie' => 4.3, 'typ' => 'Plagát'],
        ['kategoria_id' => 3, 'meno' => 'Tričko The Wichter', 'popis' => 'Bavlnené tričko s logom The Wichter.', 'info' => 'Pohodlné tričko vyrobené zo 100% bavlny, ktoré vydrží nekonečné hodiny hrania aj bežné nosenie. Na hrudi dominuje ikonické logo The Wichter, vytlačené technológiou, ktorá nepraská ani po mnohých praniach. Strih je navrhnutý tak, aby sedel každej postave, a tmavošedá farba sa hodí k čomukoľvek. Ukážte svetu, že ste pripravení na lov monštier.', 'cena' => 29.99, 'obrazok' => 'trickoWichter.webp', 'doplnkove_info' => 'Veľkosti S-XXL, 100% bavlna', 'pocet_na_sklade' => 90, 'hodnotenie' => 4.6, 'typ' => 'Oblečenie'],
        ['kategoria_id' => 3, 'meno' => 'Hrnček The Wichter', 'popis' => 'Keramický hrnček s motívom The Wichter.', 'info' => 'Hrnček pre skutočných bojovníkov, ktorí potrebujú svoju dávku kofeínu pred každou dôležitou misiou. Klasický keramický dizajn dopĺňa detailný vizuál z hry, ktorý zachytáva drsnú povahu sveta The Wichter. Hrnček má ergonomické ucho a ideálny objem pre vašu obľúbenú kávu. Odolný voči vysokým teplotám aj častému používaniu.', 'cena' => 14.99, 'obrazok' => 'wichterHrncek.webp', 'doplnkove_info' => '330ml', 'pocet_na_sklade' => 110, 'hodnotenie' => 4.4, 'typ' => 'Hrnček'],
        ['kategoria_id' => 3, 'meno' => 'Zlatý hrnček The Wichter', 'popis' => 'Limitovaný zlatý hrnček The Wichter.', 'info' => 'Skutočný klenot v našej ponuke. Tento hrnček s objemom 400ml je pokrytý špeciálnym zlatým povlakom, ktorý mu dodáva majestátny vzhľad. Na prednej strane je vygravírovaný znak školy vlka, čo z neho robí výnimočný kúsok pre zberateľov. Kvôli zlatému povrchu odporúčame výhradne ručné umývanie, aby si hrnček zachoval svoj kráľovský lesk po celé roky.', 'cena' => 34.99, 'obrazok' => 'wichterHrncek2.webp', 'doplnkove_info' => '400ml, zlatý povlak', 'pocet_na_sklade' => 40, 'hodnotenie' => 4.9, 'typ' => 'Hrnček'],

        // Figúrky (kategoria_id: 4)
        ['kategoria_id' => 4, 'meno' => 'Figúrka All of Them Part III: Ellie', 'popis' => 'Detailná figúrka postavy Ellie z hry All of Them Part III.', 'info' => 'Táto zberateľská figúrka zachytáva Ellie v jej najikonickejšom momente z tretieho dielu. Každý detail, od záplat na jej oblečení až po výraz tváre a škrabance na jej gitare, bol starostlivo vymodelovaný podľa herných predlôh. Figúrka je vyrobená z vysokokvalitného PVC a stojí na stabilnom podstavci s logom hry. Ideálny stredobod pre každú poličku s hrami, ktorý pripomína emocionálnu silu tejto série.', 'cena' => 44.99, 'obrazok' => 'FigurkaAllOfThemIII.webp', 'doplnkove_info' => '20cm, PVC', 'pocet_na_sklade' => 45, 'hodnotenie' => 4.9, 'typ' => 'Plast'],
        ['kategoria_id' => 4, 'meno' => 'Plyšák Vlad z Megaboing', 'popis' => 'Mäkký plyšový Vlad z hry Megaboing.', 'info' => 'Kto povedal, že retro hrdinovia nemôžu byť prítulní? Tento plyšový Vlad z Megaboingu je vyrobený z extra mäkkého polyesteru, ktorý je príjemný na dotyk. Vďaka svojim rozmerom 30 cm je ideálnym spoločníkom nielen pre deti, ale aj ako vtipný doplnok na herné kreslo. Plyšák je odolný, bezpečný a zachováva si svoj tvar aj po poriadnom stlačení – presne ako Vlad v hre, keď dopadne na pružinu.', 'cena' => 24.99, 'obrazok' => 'plysakMegaboing.webp', 'doplnkove_info' => '30cm, polyester', 'pocet_na_sklade' => 70, 'hodnotenie' => 4.7, 'typ' => 'Plyšové'],
        ['kategoria_id' => 4, 'meno' => 'Figúrka Football 26: Alexander-Arnold', 'popis' => 'Figúrka hráča Alexander-Arnold z Football 26.', 'info' => 'Autentická figúrka jedného z najlepších futbalistov moderných čias. Trent hrá za špičkový španielsky klub a vďaka svojim dychberúcim výkonom sa stal jednou z tvárí moderného futbalu. Figúrka zachytáva jeho charakteristický postoj pri zahrávaní priameho kopu. Vyrobená z prémiového vinylu s ručne maľovanými detailmi dresu a kopačiek. Povinný kúsok pre každého fanúšika Football 26 a milovníka krásneho športu.', 'cena' => 29.99, 'obrazok' => 'figurkaFutbalista.webp', 'doplnkove_info' => '30cm, kvalitný plast, ručná práca', 'pocet_na_sklade' => 60, 'hodnotenie' => 4.6, 'typ' => 'Vinyl'],

        // Mix
        ['kategoria_id' => 1, 'meno' => 'Mafia 1: The City of Found Hell', 'popis' => 'Originálny prvý diel legendárnej mafiánskej série.', 'info' => 'Klasická príbehová akčná hra zasadená do 30. rokov v preslávenom meste Found Hell. Sleduj osud taxikára Angela Thomasa, ktorý sa nečakane dostane do sveta organizovaného zločinu. Čakajú ťa filmový príbeh, realistická atmosféra, jazda historickými autami a intenzívne prestrelky v štýle starej školy.', 'obrazok' => 'MafiaHra.webp', 'cena' => 29.99, 'doplnkove_info' => 'PS6, PC, YBOX 180', 'pocet_na_sklade' => 66, 'hodnotenie' => 4.8, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'Mafia 2: The American Nightmare', 'popis' => 'Pokračovanie obľúbenej mafiánskej hry Mafia z prostredia Ameriky.', 'info' => 'Pokračovanie legendárnej série ťa zavedie do 40. a 50. rokov v meste Empire Bay. Sleduj príbeh Viliama Cazetty, ktorý sa zapletie do kriminálneho podsvetia v snahe o lepší život. Hra ponúka silný príbeh, detailné mestské prostredie, jazdu dobovými autami a akčné misie plné zvratov.', 'cena' => 49.99, 'obrazok' => 'Mafia2Hra.webp', 'doplnkove_info' => 'PC, PS6, PS7, YBOX Series, Steak Deck', 'pocet_na_sklade' => 51, 'hodnotenie' => 4.1, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'Tractor Farm 26', 'popis' => 'Oddychová farmárska hra pre každého nadšenca traktorov.', 'info' => 'Realistický farmársky simulátor, v ktorom buduješ a spravuješ vlastnú farmu. Oráš polia, pestuješ plodiny, staráš sa o zvieratá a používaš moderné poľnohospodárske stroje. Hra ponúka otvorený svet, ekonomický systém a detailnú simuláciu farmárskeho života.', 'cena' => 39.99, 'obrazok' => 'TractorFarm26.webp', 'doplnkove_info' => 'PC, PS6, PS7, Ybox 180, Ybox Series M, Nontend', 'pocet_na_sklade' => 88, 'hodnotenie' => 4.4, 'typ' => 'Simulátor'],
        ['kategoria_id' => 1, 'meno' => 'YourDestroy', 'popis' => 'Legendárna kockatá hra, ktorá spája všetky generácie a prináša zábavu do každej rodiny.', 'info' => 'Legendárny sandbox, v ktorom si tvoríš vlastný svet z blokov - od jednoduchých domčekov až po obrovské mestá a mechanické stroje. Ťaž, stavaj, objavuj a prežívaj v nekonečnom otvorenom svete plnom dobrodružstva, kreativity a nečakaných výziev. Každý svet je jedinečný a každý štart je nový príbeh.', 'cena' => 34.99, 'obrazok' => 'YourDestroy.webp', 'doplnkove_info' => 'PC, PS6, PS7, Nontend, Ybox 180, Ybox Series M, Steak Deck, GameGirl', 'pocet_na_sklade' => 211, 'hodnotenie' => 4.9, 'typ' => 'Adventúra'],
        ['kategoria_id' => 1, 'meno' => 'Life Shipping 2 - In The Mountains', 'popis' => 'Doručovanie balíkov nikdy nebolo zábavnejšie. Precestuj celú Ameriku s Normanom a jeho balíkmi.', 'info' => 'Atmosférická dobrodružná hra o doručovaní zásielok v rozbitom svete budúcnosti. Preskúmavaj rozsiahle krajiny, prekonávaj prekážky a spájaj izolované komunity. Dôraz na príbeh, osamelosť a prepojenie medzi hráčmi.', 'obrazok' => 'LifeShipping.webp', 'cena' => 59.99, 'doplnkove_info' => 'PS7, PC, YBOX Series M, Steak Deck', 'pocet_na_sklade' => 58, 'hodnotenie' => 4.5, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'Cycling Rush', 'popis' => 'Cyklistická pretekárka hra pre nadšencov bicyklov po celom svete.', 'info' => 'Športová cyklistická hra, kde sa zúčastňuješ profesionálnych pretekov po celom svete. Spravuj energiu jazdcov, taktizuj v pelotóne a bojuj o víťazstvo v etapách. Kombinuje rýchlosť, stratégiu a pretekársku atmosféru.', 'cena' => 22.99, 'obrazok' => 'CyclingRush.webp', 'doplnkove_info' => 'PC, Nontend, Steak Deck', 'pocet_na_sklade' => 40, 'hodnotenie' => 3.4, 'typ' => 'Športové'],
        ['kategoria_id' => 1, 'meno' => 'Driving Europe Simulator', 'popis' => 'Riadenie kamiónu naprieč celým kontinentom nikdy nebol zábavnejšie.', 'info' => 'Realistický kamiónový simulátor zasadený do európskych ciest a diaľnic. Prepravuj náklady, buduj vlastnú dopravnú firmu a objavuj mestá naprieč Európou. Dôraz na realistickú jazdu, ekonomiku a dlhé trasy.', 'cena' => 39.99, 'obrazok' => 'DrEuS.webp', 'doplnkove_info' => 'PC, PS7, Ybox Series M, Nontend, Steak Deck', 'pocet_na_sklade' => 68, 'hodnotenie' => 4.6, 'typ' => 'Simulátor'],
        ['kategoria_id' => 1, 'meno' => 'Dunk 26', 'popis' => 'Basketbalová hra, ktorá prináša revolučný gameplay jednej z najpopulárnejších športov sveta.', 'info' => 'Dynamická basketbalová športová hra, kde preberáš kontrolu nad tímom a bojuješ o titul šampióna. Rýchle zápasy, realistická fyzika lopty, kariérny režim a taktická hrateľnosť prinášajú autentický zážitok profesionálneho basketbalu.', 'cena' => 59.99, 'obrazok' => 'Dunk26.webp', 'doplnkove_info' => 'PC, PS6, PS7, Nontend, Ybox 180, Ybox Series M, Steak Deck', 'pocet_na_sklade' => 86, 'hodnotenie' => 3.8, 'typ' => 'Športové'],
        ['kategoria_id' => 1, 'meno' => 'Queendom Went Lostance', 'popis' => 'Zaži stredovek v najbrutálnejšej dobe, kedy aj princezné boli nútené bojovať.', 'info' => 'Stredoveké RPG zasadené do otvoreného sveta plného konfliktov, politiky a prežitia. Buduj svoj status v kráľovstve, rozhoduj o osude postáv a zapájaj sa do realistických súbojov. Dôraz na príbeh, voľby a atmosféru stredoveku. Každé rozhodnutie má svoju váhu a môže rozhodnúť.', 'cena' => 49.99, 'obrazok' => 'QueendomWentLostance.webp', 'doplnkove_info' => 'PC, PS6, PS7, Nontend, Ybox 180, Ybox Series M, Steak Deck, GameGirl', 'pocet_na_sklade' => 145, 'hodnotenie' => 4.8, 'typ' => 'RPG'],
        ['kategoria_id' => 1, 'meno' => 'ICE 26', 'popis' => 'Mrazivá hra plná tvrdého amerického hokeja.', 'info' => 'Rýchla a realistická hokejová športová hra. Ovládaj svoj tím v napínavých zápasoch, trénuj hráčov a bojuj o víťazstvo v lige. Ponúka autentickú hrateľnosť, fyziku kontaktov a dynamické herné situácie.', 'obrazok' => 'ice26.webp', 'cena' => 59.99, 'doplnkove_info' => 'PS7, PC, YBOX Series M, Steak Deck', 'pocet_na_sklade' => 47, 'hodnotenie' => 4.2, 'typ' => 'Športové'],
        ['kategoria_id' => 3, 'meno' => 'Originálny hrnček Queendom Went Lostance', 'popis' => 'Keramický hrnček s motívom stredovekej hry Queendom Went Lostance', 'info' => 'Tento úžasný kúsok nesmie chýbať vo vašej zbierke. Jedná sa o precízne navrhnutý stredoveký hrnček s kvalitnou potlačou. Overené odborníkmi.', 'cena' => 12.49, 'obrazok' => 'QWLhrncek.webp', 'doplnkove_info' => '330ml', 'pocet_na_sklade' => 54, 'hodnotenie' => 4.6, 'typ' => 'Hrnček'],
        ['kategoria_id' => 3, 'meno' => 'Queendom Went Lostance Merch Box: LIMITED VERSION', 'popis' => 'Limitka z obľúbenej stredovekej hry.', 'info' => 'Limitka z obľúbenej stredovekej hry. Obsahuje všetko, čo by mal verný fanúšik tejto hry vlastniť. Od hrnčeku, pinov, posteru, originál potlačenej mapy, až po tričko alebo art knihu.', 'cena' => 79.99, 'obrazok' => 'QWLMerchBox.webp', 'doplnkove_info' => 'Obsahuje všetko čo si viete predstaviť a ešte viac.', 'pocet_na_sklade' => 33, 'hodnotenie' => 4.5, 'typ' => 'Box'],
        ['kategoria_id' => 3, 'meno' => 'Life Shipping 2 Small Merch Box', 'popis' => 'Merch box doručovateľkej hry plný skvelého merchu', 'info' => 'Obsahuje samé cool veci, ktoré by mal vlastniť každý, kto je fanúšik hry Life Shipping. Tento produkt je certifikovaný vývojarom hry.', 'cena' => 24.99, 'obrazok' => 'LifeShippingMerchBoxSmall.webp', 'doplnkove_info' => 'Produkt obsahuje základný merch hry.', 'pocet_na_sklade' => 83, 'hodnotenie' => 4.4, 'typ' => 'Box'],
        ['kategoria_id' => 3, 'meno' => 'Life Shipping 2 Big Merch Box', 'popis' => 'Merch box doručovateľkej hry plný úžasného merchu', 'info' => 'Obsahuje samé cool veci, ktoré by mal vlastniť každý, kto je fanúšik hry Life Shipping. Tento produkt je certifikovaný vývojarom hry. Tento box je rozšírený o ďalšie veci oproti jeho staršej a menšej verzii.', 'cena' => 49.99, 'obrazok' => 'LifeShippingMerchBoxBig.webp', 'doplnkove_info' => 'Produkt obsahuje rozšírený merch hry.', 'pocet_na_sklade' => 62, 'hodnotenie' => 4.7, 'typ' => 'Box'],
        ['kategoria_id' => 4, 'meno' => 'Figúrka princezny z Queendom Went Lostance', 'popis' => 'Detailná figúrka v bojovej póze princezny.', 'info' => 'Táto zberateľská figúrka je jedinečná a bojovná.', 'cena' => 29.99, 'obrazok' => 'QWLfigurka.webp', 'doplnkove_info' => '25cm, PVC', 'pocet_na_sklade' => 27, 'hodnotenie' => 4.9, 'typ' => 'Plast'],
        ['kategoria_id' => 4, 'meno' => 'Cestovná figúrka Normana z Life Shipping', 'popis' => 'Známa figúrka poštára Normana.', 'info' => 'Toto je zberateľsk figúrka, ktorú treba mať.', 'cena' => 27.99, 'obrazok' => 'LifeShippingFigurka.webp', 'doplnkove_info' => '24cm, PVC', 'pocet_na_sklade' => 44, 'hodnotenie' => 4.3, 'typ' => 'Plast'],
        ['kategoria_id' => 4, 'meno' => 'Futbalová figúrka anglického futbalistu', 'popis' => 'Detská hračkárska figúrka anglického futbalistu.', 'info' => 'Kto povedal, že deti sa nemôžu hrať s figúrkami. Táto futbalová postavička predstavuje anglického futbalistu priamo na ihrisku.', 'cena' => 9.99, 'obrazok' => 'Football26RedFigurka.webp', 'doplnkove_info' => '10cm', 'pocet_na_sklade' => 122, 'hodnotenie' => 3.7, 'typ' => 'Vinyl']
        ]);
    }
}
